### ISSUE TITLE
Fails to build with latest nightly

### ISSUE THREAD

**Issue by atombender** [zhihu/rucene#1]
Rucene also fails to build with the stable channel (due to the use of `#[feature]`), so I tried the nightly release:

```
$ cargo build
   Compiling rucene v0.1.0
error[E0432]: unresolved import `std::boxed::FnBox`
  --> /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/rucene-0.1.0/src/core/util/thread_pool.rs:27:5
   |
27 | use std::boxed::FnBox;
   |     ^^^^^^^^^^^^^^^^^ no `FnBox` in `boxed`

$ rustc --version
rustc 1.41.0-nightly (59947fcae 2019-12-08)
```

**Comment by sunxiaoguang** [comment]
Hi Alexander,

Thank you for reporting this issue. Could you please try building rucene with rust nightly-2019-10-28 which is specified in rust-toolchain? FnBox was removed recently and somehow your cargo is not using rust version specified in rust-toolchain. 

Please let me know if you still have issues with it after switching to nightly-2019-10-28. And here are the commit and issue related to removing of FnBox. 
https://github.com/rust-lang/rust/pull/62043
https://github.com/rust-lang/rust/issues/28796

**Comment by atombender** [comment]
Sorry, wasn't aware of the `rust-toolchain` file. Installing that nightly doesn't resolve anything, unfortunately:

```
$ rustup run nightly-2019-10-28 cargo build
   Compiling rucene v0.1.0
error[E0432]: unresolved import `std::boxed::FnBox`
  --> /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/rucene-0.1.0/src/core/util/thread_pool.rs:27:5
   |
27 | use std::boxed::FnBox;
   |     ^^^^^^^^^^^^^^^^^ no `FnBox` in `boxed`

error: aborting due to previous error
```

**Comment by sunxiaoguang** [comment]
Can you try rustc --version to check what's the actual version it is using?

**Comment by atombender** [comment]
Sure:

```
$ rustc --version
rustc 1.40.0-nightly (95f437b3c 2019-10-27)
$ rustup which rustc
/Users/alex/.rustup/toolchains/nightly-2019-10-28-x86_64-apple-darwin/bin/rustc
```

Not sure why the discrepancy (2019-10-27 vs. 2019-10-28) here.

**Comment by sunxiaoguang** [comment]
Hm, that's weird. BTW: 2019-10-27 is the actual build date which is correct.

It works here and we are both using Mac so there shouldn't be anything related to specific platform.
![image](https://user-images.githubusercontent.com/3982329/70495583-ed3cc700-1b48-11ea-8ef7-d415fc36afe0.png)

Sorry that I'm kind of very busy right now and will come back later with this issue soon. Thank you.

**Comment by atombender** [comment]
Thanks!

**Comment by sunxiaoguang** [comment]
Hi Alexander, 

I finally know what's happening now. I overlooked that you were using `rucene` in your project and the compiler is complaining about a very old version which is still using `FnBox`. 

The root cause was that we haven't published any update to crates.io for quite some time. In order to fix this issue, I just published a new version with latest updates. Please run cargo update to update it, Sorry for the inconvenience, hopefully we can put some more resources to maintain a release cycle later on.

**Comment by atombender** [comment]
Sorry, should have been explicit; I am indeed trying to import Rucene into an app. Works now, thanks for the fix!

**Comment by sunxiaoguang** [comment]
> Sorry, should have been explicit; I am indeed trying to import Rucene into an app. Works now, thanks for the fix!

Thank you for trying `rucene`. If you have any questions about using it, please don't hesitate to let me know.
