### ISSUE TITLE
Is this project the whole engine of zhihu search or just a central library of it?

### ISSUE THREAD

**Issue by godlockin** [zhihu/rucene#14]
the difference is:
if it's a whole engine of it, we may need to deploy multiple instances by maybe docker or some to ensure the HA and distribution then. 
if it just a lib for the engine, (like the lucene against elasticsearch/solr) do we have plan to make the whole engine open source then?

**Comment by sunxiaoguang** [comment]
Rucene is the core IR library used in the search engine that powers Zhihu Search. Unfortunately the search engine were tightly coupled with many internal components which makes it very hard to work out side of Zhihu.

**Comment by godlockin** [comment]
what a shame...

hope it will be refactored into a independent project and of cuz be open source then lol~
